name: Actualizar Feed Roku

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install curl_cffi beautifulsoup4

      - name: Ejecutar Extractor
        run: python generar_feed_roku.py

      - name: Guardar y subir feed actualizado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feed_roku.json
          git commit -m "Auto-update feed Roku" || exit 0
          git push
